### ISSUE TITLE
Different distribution types of randomness/probability

### ISSUE THREAD

**Issue by Folas1337** [AutismFather/mobsizerandomizer#1]
Instead of having equal chances of mobs scaling across the board (if you scale mobs between 0.8 and 1.2 times their size, you have an equal chance to get a 0.8x scaled mob as a 1.0x size scaled mob), how about adding different algorithms?

So the default and if you configure nothing would be what we have right now which I think is called uniform, source: <https://www.theacetutors.com/blog/probability-distribution-cheat-sheet>

But according to that source we could also have a normal distribution and and exponential.

So in the config I would imagine this:
```yaml
mobs:
  wither:
    max: 1
    min: 1
    distribution: uniform
  cow:
    max: 1.2
    min: 0.7
    distribution: normal
  pig:
    max: 1.3
    min: 0.8
    distribution: leftexponential
```

Where "leftexponential" favors the minimum size mobs, so you'd have a lot of smaller pigs here and less of the bigger sized and "rightexponential" would be the exact opposite.

You do not have to pick those names exactly, they're just an idea of mine. I'm also not a mathematician so I could be very wrong with all the terms I used.

Also the average of both max and min should be the middle of those algorithms. So if we use a normal distributions as for cows, the size you would see the most on average would be 0.95x (which is 1.2+0.7/2).

I hope that all makes sense, if you need more input let me know :)
